### ISSUE TITLE
Not all theme unit tests are passed

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#41]
Here's links to dev and prod instances of theme tests, see:
https://clas-pages.uncc.edu/theme-test01
http://clas-incubator-wp.uncc.edu/theme-test01/

Here are some tests that are not passing:
https://clas-pages.uncc.edu/theme-test01/blog/2013/01/05/markup-title-with-markup/
https://clas-pages.uncc.edu/theme-test01/blog/2012/01/07/template-sticky/
-add .sticky class
https://clas-pages.uncc.edu/theme-test01/blog/2012/01/08/template-paginated/
-this post should be paginated
https://clas-pages.uncc.edu/theme-test01/blog/2010/02/05/post-format-quote/
-update css to: 

``` css
#content blockquote, .sidebar blockquote, 
#footer blockquote {`
    padding: 0.5em;
    margin: 0 .5em 0 .5em;
    border-left: solid 1px #ccc;
    font-size: 1.05em;
   line-height: 1.2em;
}
```
