### ISSUE TITLE
Refine css for post date and attribution

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#42]
Update css and listing HTML for post date and attribution so that there are separate css classes for entry-date and entry-author

``` CSS
#content .entry-meta {
    font-size: .8em;
    color: #333333;
    padding: 0.1em 0 0.5em 0;
}

#content  .entry-date {};
#content  .entry-author {};
```
