### ISSUE TITLE
Header image height constrained to 100px

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#47]
Header image height is always 100px.  Issue seems to have started with the update to WordPress 4.8.

CSS that seems to define this height is:
```css
#header .masthead {
     min-height:100px;
}
```
Have tried to change to:
```css
#header .masthead {
     min-width:100% !important;
}
```
